<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<!-- Generated by phpDocumentor on {$date}  -->
		<title>{$title}</title>
		<meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'/>
		<script src="media/frameset.js" type="text/javascript" />;</script>
	</head>
	<frameset cols="200,*">
	{if $function_count > 0 && $subpackage_count > 1}
		<frameset rows="150,*,120">
			<frame src="li_packages.html" name="li_packages">
			<frame src="li_classes.html" name="li_classes">
			<frame src="li_functions.html" name="li_functions">
		</frameset>
	{elseif $function_count < 1 && $subpackage_count < 2}
		<frame src="li_ab.html" name="li_classes">
	{else}
		<frameset rows="150,*">
			<frame src="li_packages.html" name="li_packages">
			<frame src="li_classes.html" name="li_classes">
		</frameset>
	{/if}
		<frame src="classtrees_ab.html" name="right" id="mainframe">
		<noframes>
			<h2>Frame Alert</h2>
			This document is designed to be viewed using the frames feature.
			If you see this message, you are using a non-frame-capable web client.
		</noframes>
	</frameset>
</html>